author = "千夜同学"

baseURL = "http://70data.net"
title = "千夜同学"
copyright = "Copyright © 2012–2025"

enableRobotsTXT = true

defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
hasCJKLanguage = true

theme = "tokiwa"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# uglyurls = true
disablePathToLower = false
canonifyurls = true
relativeURLs = false

summaryLength = 9
enableEmoji = true

[pagination]
  pagersize = 9

[markup]

[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 2

[params]
bannerFont = "fonts/exampleFont"
description = "看脚下一片黑暗 望头顶星光璀璨"
env = "production"
favicon = "/img/favicon-32x32.png"
fuse = true
math = true
useChineseFonts = true
postDateFormat = "2006-1-2"

[params.utteranc]
  enable = true

[params.social]
instagram="http://example.com/"
bilibili="http://example.com/"
weibo="http://example.com/"
zhihu="http://example.com/"
twitter="http://twitter.com/"
gitlab="http://gitlab.com/"
youtube="http://youtube.com/"
github="http://github.com/"

[menu]

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]
