baseURL = "http://70data.net"
title = "千夜同学"

theme = "noteworthy"
metadataformat = "yaml"

defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"

enableRobotsTXT = true

canonifyurls = true
relativeURLs = false
uglyurls = true

disableKinds = ["RSS", "taxonomyTerm"]

disablePathToLower = true

enableEmoji = true

hasCJKLanguage = true
preserveTaxonomyNames = true

paginate = 9 # Set the number of posts to show before overflowing to the next page.
summaryLength = 9 # Configure how long the post summary should be on the homepage.

[params]
	# general information
	author = "千夜同学"
	keywords = "千夜同学"
	subTitle = "看脚下一片黑暗 望头顶星光璀璨"
	description = ""
	copyright = ""
	# repository
	provider = "GitHub"
	repo_url = "https://github.com/70data/blog"
	favicon = ""
	logo = "images/logo.jpg"
	permalink = "#"
	# custom assets
	custom_css = []
	custom_js  = []
	# syntax highlighting theme
	highlight_css  = ""
	scrollTop = true
	# reward button, comment this to disable it
	reward = true
	math = true
	showReadMore = true
	# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
	enableKofi = false
	[params.palette]
		primary = "red"
		accent  = "teal"
	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[taxonomies]
	tag = "tags"

[markup]
	[markup.highlight]
		style = "monokailight"
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 2
	# Set to false to disallow raw HTML in markdown files
	[markup.goldmark.renderer]
		unsafe = true

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1
