author = "千夜同学"

baseURL = "http://70data.net"
title = "千夜同学"
copyright = "Copyright © 2012–2022"

defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
hasCJKLanguage = true

theme = "tokiwa"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

# uglyurls = true
disablePathToLower = false
canonifyurls = true
relativeURLs = false

enableEmoji = true

enableRobotsTXT = true
paginate = 9
summaryLength = 9

[markup]

[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 2

[params]
bannerFont = "fonts/exampleFont" 
description = "看脚下一片黑暗 望头顶星光璀璨" 
env = "production"
favicon = "img/favicon-32x32.png" 
fuse = true
math = true
useChineseFonts = true 
postDateFormat = "2006-1-2"

[menu]

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[social]
# mail = "mailto:anon@example.com"
# github = "http://github.com/"
# gitlab = "http://gitlab.com/"
# zhihu = "http://example.com/"
# youtube = "http://youtube.com/"
# bilibili = "http://example.com/"
# instagram = "http://example.com/"
# twitter = "http://twitter.com/"
# weibo = "http://example.com/"

[outputs]
home = ["HTML", "RSS", "JSON"]

